name: Teste de Carga com JMeter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do reposit칩rio
      uses: actions/checkout@v3

    - name: Instalar Java (necess치rio para rodar o JMeter)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Baixar Apache JMeter
      run: |
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 jmeter

    - name: Executar teste JMeter
      run: |
        ./jmeter/bin/jmeter -n -t src/test/java/com/Atividade/meutestes.jmx -l resultados.jtl

    - name: Gerar relat칩rio HTML
      run: |
        apache-jmeter-5.6.3/bin/jmeter -g resultado.jtl -o relatorio-html

    - name: Publicar relat칩rio como artefato
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-jmeter
        path: relatorio-html
