name: Testes Automatizados

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Rodar testes com Maven (com debug)
      run: mvn clean test -e -X

    - name: Listar relat처rios de testes
      run: ls -l target/surefire-reports || echo "Pasta n찾o encontrada"

    - name: Mostrar relat처rios de testes (se existirem)
      run: cat target/surefire-reports/*.txt || echo "Nenhum relat처rio para mostrar"
